export class profiles{
    idprofile:string;
    tittle:string;
    first_name:string;
    second_name:string;
    first_lastname:string;
    second_lastname:string;
    day_of_birthday:string;
    nationality:string;
    gender:string;
    etnia:string;
    bank:string;
    account:string;    
    type_account:string;    
    marital_status:string;
    dpi:string;
    nit:string;
    igss:string;
    irtra:string;
    status:string;
    //Key
    id_profile:number;
    //Details
    idprofile_details:number;
    english_level:string;
    transport:string;
    start_date:string;
    unavailable_days:string;
    marketing_campaing:string;
    first_lenguage:string;
    second_lenguage:string;
    third_lenguage:string;
    //Contact
    idcontact_details:number;
    primary_phone:string;
    secondary_phone:string;
    address:string;
    city:string;
    email:string;
    //emergency
    idemergency_details:number;
    emergency_first_name:string;
    emergency_second_name:string;
    emergency_first_lastname:string;
    emergency_second_lastname:string;
    emergency_phone:string;
    relationship:string;
    //affinity
    idaffinity_details:number;
    affinity_first_name:string;
    affinity_second_name:string;
    affinity_first_lastname:string;
    affinity_second_lastname:string;
    affinity_phone:string;
    affinity_relationship:string;
    //medical
    medical_treatment:string;
    medical_prescription:string;
    //education
    current_level:string;
    futher_education:string;
    currently_studing:string;
    institution_name:string;
    degree:string;
}